# Server
server.port=8080

# Spring application
spring.application.name=api-gateway

# Import shared config from Config Server repo
spring.config.import=shared-config.properties

# Eureka Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Spring Cloud Gateway discovery-based routing
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# Static route for user-service (optional if discovery locator is enabled)
spring.cloud.gateway.routes[0].id=user-service
spring.cloud.gateway.routes[0].uri=lb://user-service
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/users/**
spring.cloud.gateway.routes[0].filters[0]=Name=AuthenticationFilter
