spring.application.name=config-server

server.port=8888

spring.cloud.config.server.git.uri=https://github.com/your-username/task-config-repo
spring.cloud.config.server.git.clone-on-start=true
jwt.secret=nL0++CqZqYZw94Dojqt5Nzp3zFs7QL6L5XrrE4OLZtNG6S3Lfw4k1gXfF+4wKdh3fZdPONxYQl+Vk4oWhrZHg+g==
